// Account-screen text as a phone's text reader returns it (line breaks, stray marks, the odd misread), with what
// the screenshot reader should find. Run: node tests/run-scan-tests.mjs
// Expected keys: program, balance, tier, exp, progress, alt, mqd, member (omit a key to not check it; null = must be empty).
export default [
  // ---------- US airlines ----------
  { name: 'Delta app', text: `SkyMiles Member\nGold Medallion®\nStatus valid through Jan 31, 2028\n84,250\nmiles\nMQDs\n$11,240 of $15,000\nSkyMiles # 9012345678`,
    expect: { program: 'delta', balance: 84250, tier: 'Gold Medallion', exp: '2028-01-31', mqd: 11240, member: '9012345678' } },
  { name: 'Delta web, card named', text: `Delta Air Lines\nMy Profile\nDelta SkyMiles® Platinum American Express Card\nSilver Medallion Member\nMiles Available 132,018\nMedallion Qualification Dollars $6,880\n$3,120 more to reach Gold`,
    expect: { program: 'delta', balance: 132018, tier: 'Silver Medallion', mqd: 6880 } },
  { name: 'Delta, MQD then year', text: `Delta SkyMiles\nMQDs earned in 2026: $4,512\n120,000 miles`,
    expect: { program: 'delta', balance: 120000, mqd: 4512 } },
  { name: 'Delta, OCR slip', text: `SkyMiIes\nPlatinum Medallion\n61.400 miles\nMQD $16,250`,
    expect: { program: 'delta', balance: 61400, tier: 'Platinum Medallion', mqd: 16250 } },
  { name: 'United app', text: `MileagePlus\nPremier Gold\nMiles\n64,018\nPQP 12,450 / 18,000\nPQF 31 / 45\nMileagePlus # AB123456`,
    expect: { program: 'united', balance: 64018, tier: 'Premier Gold', progress: 12450, alt: 31, member: 'AB123456' } },
  { name: 'American', text: `AAdvantage\nPlatinum Pro\nAward miles\n45,210\nLoyalty Points\n82,000 of 125,000\nAAdvantage # 1AB2C34`,
    expect: { program: 'american', balance: 45210, tier: 'Platinum Pro', progress: 82000 } },
  { name: 'Southwest', text: `Rapid Rewards\nA-List Preferred\nAvailable points 45,980\nTier qualifying points 70,500\nQualifying flights 12`,
    expect: { program: 'southwest', balance: 45980, tier: 'A-List Preferred', progress: 70500, alt: 12 } },
  { name: 'Alaska Atmos', text: `Atmos Rewards\nAtmos Gold\n38,700 points\nStatus points 43,500\nMember number 123456789`,
    expect: { program: 'alaska', balance: 38700, tier: 'Gold', progress: 43500, member: '123456789' } },
  { name: 'JetBlue', text: `TrueBlue\nMosaic 3\n52,300 points\n150 tiles`,
    expect: { program: 'jetblue', balance: 52300, tier: 'Mosaic 3' } },
  { name: 'Frontier', text: `FRONTIER Miles\nElite Gold\nMiles 18,250`,
    expect: { program: 'frontier', balance: 18250, tier: 'Elite Gold' } },

  // ---------- International airlines ----------
  { name: 'Aeroplan', text: `Aeroplan\nAeroplan 35K\n112,400 points\nSQC 41,200 of 50,000`,
    expect: { program: 'aeroplan', balance: 112400, tier: '35K', progress: 41200 } },
  { name: 'Flying Blue', text: `Flying Blue\nGold\n78,450 Miles\n182 XP\nStatus valid until 30/04/2027`,
    expect: { program: 'flyingblue', balance: 78450, tier: 'Gold', exp: '2027-04-30' } },
  { name: 'British Airways', text: `The British Airways Club\nSilver\nAvios 96,320\nTier status until 05/04/2027`,
    expect: { program: 'ba', balance: 96320, tier: 'Silver', exp: '2027-04-05' } },
  { name: 'Virgin Atlantic', text: `Flying Club\nGold\nVirgin Points 120,450`,
    expect: { program: 'virgin', balance: 120450, tier: 'Gold' } },
  { name: 'Emirates', text: `Emirates Skywards\nSilver\nSkywards Miles 40,120\nTier Miles 28,000\nMembership number EK 123456789`,
    expect: { program: 'emirates', balance: 40120, tier: 'Silver', member: 'EK123456789' } },
  { name: 'Singapore', text: `KrisFlyer\nKrisFlyer Elite Gold\nKrisFlyer miles 88,000`,
    expect: { program: 'singapore', balance: 88000, tier: 'Elite Gold' } },
  { name: 'Qatar', text: `Privilege Club\nPlatinum\nAvios 154,300\nQpoints 640`,
    expect: { program: 'qatar', balance: 154300, tier: 'Platinum' } },
  { name: 'Turkish', text: `Miles&Smiles\nElite Plus\nMiles 72,000`,
    expect: { program: 'turkish', balance: 72000, tier: 'Elite Plus' } },
  { name: 'Lufthansa', text: `Miles & More\nSenator\nAward miles 210,000`,
    expect: { program: 'lufthansa', balance: 210000, tier: 'Senator' } },
  { name: 'Cathay', text: `Cathay\nMembership Diamond\nAsia Miles 64,500`,
    expect: { program: 'cathay', balance: 64500, tier: 'Diamond' } },
  { name: 'Korean Air', text: `SKYPASS\nMorning Calm Premium\n152,300 miles`,
    expect: { program: 'koreanair', balance: 152300, tier: 'Morning Calm Premium' } },
  { name: 'Avianca', text: `LifeMiles\nDiamond\n45,000 LifeMiles`,
    expect: { program: 'avianca', tier: 'Diamond' } },

  // ---------- Hotels ----------
  { name: 'IHG web', text: `IHG ONE\nREWARDS\nMy Account Stays and Events Points Offers BOOK\nHello Alex,\nPlatinum Elite Member\nMember #123456789\nYOUR POINTS\n26,948\nRedeem Points\nPurchase points`,
    expect: { program: 'ihg', balance: 26948, tier: 'Platinum Elite', member: '123456789' } },
  { name: 'Marriott app', text: `Marriott Bonvoy\nTitanium Elite\n250,145\nPoints\n76 of 100 nights to Ambassador\nLifetime nights 520\nMember since 2014`,
    expect: { program: 'marriott', balance: 250145, tier: 'Titanium Elite', progress: 76 } },
  { name: 'Marriott web', text: `MARRIOTT BONVOY\nGold Elite\nPoints: 48,320\nNights this year: 32\nMember Number: 123456789`,
    expect: { program: 'marriott', balance: 48320, tier: 'Gold Elite', progress: 32, member: '123456789' } },
  { name: 'Hilton', text: `Hilton Honors\nDiamond Reserve\n120,000 Points\nNights 85\nStays 22\nStatus through 03/31/2028`,
    expect: { program: 'hilton', balance: 120000, tier: 'Diamond Reserve', progress: 85, alt: 22, exp: '2028-03-31' } },
  { name: 'Hilton, target', text: `Hilton Honors\nGold Member\nPoints 34,500\n8 of 25 nights\n12 more nights to Diamond`,
    expect: { program: 'hilton', balance: 34500, tier: 'Gold', progress: 8 } },
  { name: 'Hyatt', text: `World of Hyatt\nExplorist\nCurrent Points 45,120\nQualifying night credits 31\nBase points 52,300`,
    expect: { program: 'hyatt', balance: 45120, tier: 'Explorist', progress: 31, alt: 52300 } },
  { name: 'Wyndham', text: `Wyndham Rewards\nPlatinum\nPoints 22,000\nQualified nights 17`,
    expect: { program: 'wyndham', balance: 22000, tier: 'Platinum', progress: 17 } },
  { name: 'Choice', text: `Choice Privileges\nTitanium\n61,200 points`,
    expect: { program: 'choice', balance: 61200, tier: 'Titanium' } },
  { name: 'Accor', text: `ALL - Accor Live Limitless\nPlatinum\n12,400 Reward points\nStatus valid until 28/02/2027`,
    expect: { program: 'accor', balance: 12400, tier: 'Platinum', exp: '2027-02-28' } },
  { name: 'Best Western', text: `Best Western Rewards\nDiamond Select\n88,900 points`,
    expect: { program: 'bestwestern', balance: 88900, tier: 'Diamond Select' } },

  // ---------- Harder layouts: promos, lifetime totals, dollar values, merged columns ----------
  { name: 'Marriott promo + expiring', text: `Marriott Bonvoy\nPlatinum Elite\nEarn 2X points on your next stay\nPoints\n98,410\nPoints expiring: 0\nNights this year 51`,
    expect: { program: 'marriott', balance: 98410, tier: 'Platinum Elite', progress: 51 } },
  { name: 'Hilton lifetime', text: `Hilton Honors\nDiamond\nPoints 302,118\nLifetime points 1,204,000\nNights 61\nPoints expiring: Never`,
    expect: { program: 'hilton', balance: 302118, tier: 'Diamond', progress: 61 } },
  { name: 'United lifetime', text: `United MileagePlus\nPremier 1K\nAvailable miles 410,500\nLifetime flight miles 1,512,000\nPQP 29,100`,
    expect: { program: 'united', balance: 410500, tier: 'Premier 1K', progress: 29100 } },
  { name: 'Chase worth', text: `Ultimate Rewards\nYou have\n120,345 points\nWorth $1,504.31 with Points Boost\nEarn 3X on dining`,
    expect: { program: 'chase', balance: 120345 } },
  { name: 'Capital One cash value', text: `Capital One\nVenture X Rewards\n75,123 Miles\n= $751.23`,
    expect: { program: 'capitalone', balance: 75123 } },
  { name: 'Amex promo', text: `American Express\nMembership Rewards Points\n88,050\nEarn 5X points on flights\nPay with Points: 0.6¢ per point`,
    expect: { program: 'amex', balance: 88050 } },
  { name: 'IHG merged columns', text: `IHG ONE REWARDS My Account Stays and Events Points Offers BOOK\nHello Alex, YOUR POINTS\nPlatinum Elite Member 26,948\nMember #123456789 Redeem Points`,
    expect: { program: 'ihg', balance: 26948, tier: 'Platinum Elite', member: '123456789' } },
  { name: 'IHG app', text: `IHG One Rewards\nPlatinum Elite\n26,948 pts\nMember 123456789\nQualifying nights 22`,
    expect: { program: 'ihg', balance: 26948, tier: 'Platinum Elite', progress: 22, member: '123456789' } },
  { name: 'Hyatt globalist dates', text: `World of Hyatt\nGlobalist\nThrough Feb 28, 2028\n45,120 points\nQualifying night credits 64`,
    expect: { program: 'hyatt', balance: 45120, tier: 'Globalist', exp: '2028-02-28', progress: 64 } },
  { name: 'Alaska titanium', text: `Atmos Rewards\nAtmos Titanium\n210,000 points\nStatus points 140,000 / 135,000`,
    expect: { program: 'alaska', balance: 210000, tier: 'Titanium', progress: 140000 } },
  { name: 'Delta dark noisy', text: `SkyMiles | Gold Medallion\n84,250 mi\nMQDs $11,240\nStatus valid thru 1/31/28`,
    expect: { program: 'delta', balance: 84250, tier: 'Gold Medallion', mqd: 11240, exp: '2028-01-31' } },
  { name: 'Southwest companion', text: `Southwest Rapid Rewards\nA-List\n31,200 points\nCompanion Pass qualifying points 98,000\nTier qualifying points 40,100`,
    expect: { program: 'southwest', balance: 31200, tier: 'A-List', progress: 40100 } },

  // ---------- Card points ----------
  { name: 'Amex', text: `Membership Rewards\nPoints available\n143,212 pts\nAccount ending 31005`,
    expect: { program: 'amex', balance: 143212, member: null } },
  { name: 'Chase with partners', text: `Chase Ultimate Rewards®\n120,345 points available\nTransfer to partners: IHG One Rewards, World of Hyatt, United MileagePlus, Marriott Bonvoy`,
    expect: { program: 'chase', balance: 120345 } },
  { name: 'Citi', text: `Citi ThankYou® Points\n45,000 points\nStrata Premier ...7712`,
    expect: { program: 'citi', balance: 45000 } },
  { name: 'Capital One', text: `Venture X\nRewards balance\n75,123 miles\nCapital One Travel`,
    expect: { program: 'capitalone', balance: 75123 } },
  { name: 'Bilt', text: `Bilt Rewards\nBilt Points 32,000\nPlatinum`,
    expect: { program: 'bilt', balance: 32000 } },
  { name: 'Wells Fargo', text: `Wells Fargo Rewards\n26,410 points`,
    expect: { program: 'wellsfargo', balance: 26410 } },
  { name: 'U.S. Bank', text: `U.S. Bank Altitude Reserve\nAltitude points 54,000`,
    expect: { program: 'usbank', balance: 54000 } },
  { name: 'Bank of America', text: `Bank of America\nPremium Rewards\nAvailable points 18,400`,
    expect: { program: 'bofa', balance: 18400 } },

  // ---------- Car rental (status only) ----------
  { name: 'National', text: `Emerald Club\nExecutive Elite\nMember # 123456789`,
    expect: { program: 'national', tier: 'Executive Elite' } },
  { name: 'Hertz', text: `Hertz Gold Plus Rewards\nPresident's Circle\nPoints 1,250`,
    expect: { program: 'hertz', tier: "President's Circle" } },
];
