// Account-screen text as a phone's text reader returns it (line breaks, stray marks, the odd misread), with what
// the screenshot reader should find. Run: node tests/run-scan-tests.mjs
// Expected keys: program, balance, tier, exp, progress, alt, mqd, member (omit a key to not check it; null = must be empty).
export default [
  // ---------- US airlines ----------
  { name: 'Delta app', text: `SkyMiles Member\nGold Medallion®\nStatus valid through Jan 31, 2028\n84,250\nmiles\nMQDs\n$11,240 of $15,000\nSkyMiles # 9012345678`,
    expect: { program: 'delta', balance: 84250, tier: 'Gold Medallion', exp: '2028-01-31', mqd: 11240, member: '9012345678' } },
  { name: 'Delta web, card named', text: `Delta Air Lines\nMy Profile\nDelta SkyMiles® Platinum American Express Card\nSilver Medallion Member\nMiles Available 132,018\nMedallion Qualification Dollars $6,880\n$3,120 more to reach Gold`,
    expect: { program: 'delta', balance: 132018, tier: 'Silver Medallion', mqd: 6880 } },
  { name: 'Delta, MQD then year', text: `Delta SkyMiles\nMQDs earned in 2026: $4,512\n120,000 miles`,
    expect: { program: 'delta', balance: 120000, mqd: 4512 } },
  { name: 'Delta, OCR slip', text: `SkyMiIes\nPlatinum Medallion\n61.400 miles\nMQD $16,250`,
    expect: { program: 'delta', balance: 61400, tier: 'Platinum Medallion', mqd: 16250 } },
  { name: 'United app', text: `MileagePlus\nPremier Gold\nMiles\n64,018\nPQP 12,450 / 18,000\nPQF 31 / 45\nMileagePlus # AB123456`,
    expect: { program: 'united', balance: 64018, tier: 'Premier Gold', progress: 12450, alt: 31, member: 'AB123456' } },
  { name: 'American', text: `AAdvantage\nPlatinum Pro\nAward miles\n45,210\nLoyalty Points\n82,000 of 125,000\nAAdvantage # 1AB2C34`,
    expect: { program: 'american', balance: 45210, tier: 'Platinum Pro', progress: 82000 } },
  { name: 'Southwest', text: `Rapid Rewards\nA-List Preferred\nAvailable points 45,980\nTier qualifying points 70,500\nQualifying flights 12`,
    expect: { program: 'southwest', balance: 45980, tier: 'A-List Preferred', progress: 70500, alt: 12 } },
  { name: 'Alaska Atmos', text: `Atmos Rewards\nAtmos Gold\n38,700 points\nStatus points 43,500\nMember number 123456789`,
    expect: { program: 'alaska', balance: 38700, tier: 'Gold', progress: 43500, member: '123456789' } },
  { name: 'JetBlue', text: `TrueBlue\nMosaic 3\n52,300 points\n150 tiles`,
    expect: { program: 'jetblue', balance: 52300, tier: 'Mosaic 3' } },
  { name: 'Frontier', text: `FRONTIER Miles\nElite Gold\nMiles 18,250`,
    expect: { program: 'frontier', balance: 18250, tier: 'Elite Gold' } },

  // ---------- International airlines ----------
  { name: 'Aeroplan', text: `Aeroplan\nAeroplan 35K\n112,400 points\nSQC 41,200 of 50,000`,
    expect: { program: 'aeroplan', balance: 112400, tier: '35K', progress: 41200 } },
  { name: 'Flying Blue', text: `Flying Blue\nGold\n78,450 Miles\n182 XP\nStatus valid until 30/04/2027`,
    expect: { program: 'flyingblue', balance: 78450, tier: 'Gold', exp: '2027-04-30' } },
  { name: 'British Airways', text: `The British Airways Club\nSilver\nAvios 96,320\nTier status until 05/04/2027`,
    expect: { program: 'ba', balance: 96320, tier: 'Silver', exp: '2027-04-05' } },
  { name: 'Virgin Atlantic', text: `Flying Club\nGold\nVirgin Points 120,450`,
    expect: { program: 'virgin', balance: 120450, tier: 'Gold' } },
  { name: 'Emirates', text: `Emirates Skywards\nSilver\nSkywards Miles 40,120\nTier Miles 28,000\nMembership number EK 123456789`,
    expect: { program: 'emirates', balance: 40120, tier: 'Silver', member: 'EK123456789' } },
  { name: 'Singapore', text: `KrisFlyer\nKrisFlyer Elite Gold\nKrisFlyer miles 88,000`,
    expect: { program: 'singapore', balance: 88000, tier: 'Elite Gold' } },
  { name: 'Qatar', text: `Privilege Club\nPlatinum\nAvios 154,300\nQpoints 640`,
    expect: { program: 'qatar', balance: 154300, tier: 'Platinum' } },
  { name: 'Turkish', text: `Miles&Smiles\nElite Plus\nMiles 72,000`,
    expect: { program: 'turkish', balance: 72000, tier: 'Elite Plus' } },
  { name: 'Lufthansa', text: `Miles & More\nSenator\nAward miles 210,000`,
    expect: { program: 'lufthansa', balance: 210000, tier: 'Senator' } },
  { name: 'Cathay', text: `Cathay\nMembership Diamond\nAsia Miles 64,500`,
    expect: { program: 'cathay', balance: 64500, tier: 'Diamond' } },
  { name: 'Korean Air', text: `SKYPASS\nMorning Calm Premium\n152,300 miles`,
    expect: { program: 'koreanair', balance: 152300, tier: 'Morning Calm Premium' } },
  { name: 'Avianca', text: `LifeMiles\nDiamond\n45,000 LifeMiles`,
    expect: { program: 'avianca', tier: 'Diamond' } },

  // ---------- Hotels ----------
  { name: 'IHG web', text: `IHG ONE\nREWARDS\nMy Account Stays and Events Points Offers BOOK\nHello Alex,\nPlatinum Elite Member\nMember #123456789\nYOUR POINTS\n26,948\nRedeem Points\nPurchase points`,
    expect: { program: 'ihg', balance: 26948, tier: 'Platinum Elite', member: '123456789' } },
  { name: 'Marriott app', text: `Marriott Bonvoy\nTitanium Elite\n250,145\nPoints\n76 of 100 nights to Ambassador\nLifetime nights 520\nMember since 2014`,
    expect: { program: 'marriott', balance: 250145, tier: 'Titanium Elite', progress: 76 } },
  { name: 'Marriott web', text: `MARRIOTT BONVOY\nGold Elite\nPoints: 48,320\nNights this year: 32\nMember Number: 123456789`,
    expect: { program: 'marriott', balance: 48320, tier: 'Gold Elite', progress: 32, member: '123456789' } },
  { name: 'Hilton', text: `Hilton Honors\nDiamond Reserve\n120,000 Points\nNights 85\nStays 22\nStatus through 03/31/2028`,
    expect: { program: 'hilton', balance: 120000, tier: 'Diamond Reserve', progress: 85, alt: 22, exp: '2028-03-31' } },
  { name: 'Hilton, target', text: `Hilton Honors\nGold Member\nPoints 34,500\n8 of 25 nights\n12 more nights to Diamond`,
    expect: { program: 'hilton', balance: 34500, tier: 'Gold', progress: 8 } },
  { name: 'Hyatt', text: `World of Hyatt\nExplorist\nCurrent Points 45,120\nQualifying night credits 31\nBase points 52,300`,
    expect: { program: 'hyatt', balance: 45120, tier: 'Explorist', progress: 31, alt: 52300 } },
  { name: 'Wyndham', text: `Wyndham Rewards\nPlatinum\nPoints 22,000\nQualified nights 17`,
    expect: { program: 'wyndham', balance: 22000, tier: 'Platinum', progress: 17 } },
  { name: 'Choice', text: `Choice Privileges\nTitanium\n61,200 points`,
    expect: { program: 'choice', balance: 61200, tier: 'Titanium' } },
  { name: 'Accor', text: `ALL - Accor Live Limitless\nPlatinum\n12,400 Reward points\nStatus valid until 28/02/2027`,
    expect: { program: 'accor', balance: 12400, tier: 'Platinum', exp: '2027-02-28' } },
  { name: 'Best Western', text: `Best Western Rewards\nDiamond Select\n88,900 points`,
    expect: { program: 'bestwestern', balance: 88900, tier: 'Diamond Select' } },

  // ---------- Harder layouts: promos, lifetime totals, dollar values, merged columns ----------
  { name: 'Marriott promo + expiring', text: `Marriott Bonvoy\nPlatinum Elite\nEarn 2X points on your next stay\nPoints\n98,410\nPoints expiring: 0\nNights this year 51`,
    expect: { program: 'marriott', balance: 98410, tier: 'Platinum Elite', progress: 51 } },
  { name: 'Hilton lifetime', text: `Hilton Honors\nDiamond\nPoints 302,118\nLifetime points 1,204,000\nNights 61\nPoints expiring: Never`,
    expect: { program: 'hilton', balance: 302118, tier: 'Diamond', progress: 61 } },
  { name: 'United lifetime', text: `United MileagePlus\nPremier 1K\nAvailable miles 410,500\nLifetime flight miles 1,512,000\nPQP 29,100`,
    expect: { program: 'united', balance: 410500, tier: 'Premier 1K', progress: 29100 } },
  { name: 'Chase worth', text: `Ultimate Rewards\nYou have\n120,345 points\nWorth $1,504.31 with Points Boost\nEarn 3X on dining`,
    expect: { program: 'chase', balance: 120345 } },
  { name: 'Capital One cash value', text: `Capital One\nVenture X Rewards\n75,123 Miles\n= $751.23`,
    expect: { program: 'capitalone', balance: 75123 } },
  { name: 'Amex promo', text: `American Express\nMembership Rewards Points\n88,050\nEarn 5X points on flights\nPay with Points: 0.6¢ per point`,
    expect: { program: 'amex', balance: 88050 } },
  { name: 'IHG merged columns', text: `IHG ONE REWARDS My Account Stays and Events Points Offers BOOK\nHello Alex, YOUR POINTS\nPlatinum Elite Member 26,948\nMember #123456789 Redeem Points`,
    expect: { program: 'ihg', balance: 26948, tier: 'Platinum Elite', member: '123456789' } },
  { name: 'IHG app', text: `IHG One Rewards\nPlatinum Elite\n26,948 pts\nMember 123456789\nQualifying nights 22`,
    expect: { program: 'ihg', balance: 26948, tier: 'Platinum Elite', progress: 22, member: '123456789' } },
  { name: 'Hyatt globalist dates', text: `World of Hyatt\nGlobalist\nThrough Feb 28, 2028\n45,120 points\nQualifying night credits 64`,
    expect: { program: 'hyatt', balance: 45120, tier: 'Globalist', exp: '2028-02-28', progress: 64 } },
  { name: 'Alaska titanium', text: `Atmos Rewards\nAtmos Titanium\n210,000 points\nStatus points 140,000 / 135,000`,
    expect: { program: 'alaska', balance: 210000, tier: 'Titanium', progress: 140000 } },
  { name: 'Delta dark noisy', text: `SkyMiles | Gold Medallion\n84,250 mi\nMQDs $11,240\nStatus valid thru 1/31/28`,
    expect: { program: 'delta', balance: 84250, tier: 'Gold Medallion', mqd: 11240, exp: '2028-01-31' } },
  { name: 'Southwest companion', text: `Southwest Rapid Rewards\nA-List\n31,200 points\nCompanion Pass qualifying points 98,000\nTier qualifying points 40,100`,
    expect: { program: 'southwest', balance: 31200, tier: 'A-List', progress: 40100 } },

  // ---------- Card points ----------
  { name: 'Amex', text: `Membership Rewards\nPoints available\n143,212 pts\nAccount ending 31005`,
    expect: { program: 'amex', balance: 143212, member: null } },
  { name: 'Chase with partners', text: `Chase Ultimate Rewards®\n120,345 points available\nTransfer to partners: IHG One Rewards, World of Hyatt, United MileagePlus, Marriott Bonvoy`,
    expect: { program: 'chase', balance: 120345 } },
  { name: 'Citi', text: `Citi ThankYou® Points\n45,000 points\nStrata Premier ...7712`,
    expect: { program: 'citi', balance: 45000 } },
  { name: 'Capital One', text: `Venture X\nRewards balance\n75,123 miles\nCapital One Travel`,
    expect: { program: 'capitalone', balance: 75123 } },
  { name: 'Bilt', text: `Bilt Rewards\nBilt Points 32,000\nPlatinum`,
    expect: { program: 'bilt', balance: 32000 } },
  { name: 'Wells Fargo', text: `Wells Fargo Rewards\n26,410 points`,
    expect: { program: 'wellsfargo', balance: 26410 } },
  { name: 'U.S. Bank', text: `U.S. Bank Altitude Reserve\nAltitude points 54,000`,
    expect: { program: 'usbank', balance: 54000 } },
  { name: 'Bank of America', text: `Bank of America\nPremium Rewards\nAvailable points 18,400`,
    expect: { program: 'bofa', balance: 18400 } },

  // ---------- Car rental (status only) ----------
  { name: 'National', text: `Emerald Club\nExecutive Elite\nMember # 123456789`,
    expect: { program: 'national', tier: 'Executive Elite' } },
  { name: 'Hertz', text: `Hertz Gold Plus Rewards\nPresident's Circle\nPoints 1,250`,
    expect: { program: 'hertz', tier: "President's Circle" } },

  // ---------- Targets, totals, and OCR slips ----------
  { name: 'Hilton: "17 nights to go" is not the count', text: `Hilton Honors\nGold\nPoints 34,500\n17 nights to go for Diamond\nNights 33`,
    expect: { program: 'hilton', progress: 33, balance: 34500 } },
  { name: 'Marriott: "nights away from" is not the count', text: `Marriott Bonvoy\nPlatinum Elite\n98,410 Points\n24 nights away from Titanium\nNights this year 51`,
    expect: { program: 'marriott', progress: 51, balance: 98410 } },
  { name: 'AA: "Loyalty Points away from" is not the count or balance',
    text: `AAdvantage\nGold\nYou are 42,000 Loyalty Points away from Platinum Pro\nLoyalty Points 83,000\nMiles 45,000`,
    expect: { program: 'american', progress: 83000, balance: 45000 } },
  { name: 'Delta: MQD Headstart is part of the total', text: `Delta SkyMiles\nGold Medallion\nMQD Headstart $2,500\nMQDs $12,400\n61,000 miles`,
    expect: { program: 'delta', mqd: 12400, balance: 61000 } },
  { name: 'Delta: total MQDs beat card spend', text: `SkyMiles\nMQDs from Delta card spend $3,200\nTotal MQDs $11,240\nMiles 40,120`,
    expect: { program: 'delta', mqd: 11240, balance: 40120 } },
  { name: 'Delta: status valid until a date', text: `SkyMiles\nPlatinum Medallion valid until Jan 31, 2028\n61,400 miles`,
    expect: { program: 'delta', tier: 'Platinum Medallion', exp: '2028-01-31', balance: 61400 } },
  { name: 'United: "Premier IK" misread', text: `MileagePlus\nPremier IK\n125,300 miles\nPQP 24,100`,
    expect: { program: 'united', tier: 'Premier 1K', balance: 125300, progress: 24100 } },
  { name: 'Flying Blue: spaced thousands', text: `Flying Blue\nGold\n78 450 Miles\nXP 182`,
    expect: { program: 'flyingblue', tier: 'Gold', balance: 78450 } },
  { name: 'Iberia: spaced thousands', text: `Iberia Club\nPlata\n12 500 Avios`,
    expect: { program: 'iberia', tier: 'Plata', balance: 12500 } },
  { name: 'Bilt: label above its number', text: `Bilt Rewards\nBilt Cash\n1,250\nPoints\n32,000`,
    expect: { program: 'bilt', balance: 32000 } },
  { name: 'Hyatt: "Exp" date', text: `World of Hyatt\nExplorist\nExp 12/31/27\n41,200 points`,
    expect: { program: 'hyatt', tier: 'Explorist', exp: '2027-12-31', balance: 41200 } },
  { name: 'United: a target on the PQP line, miles below', text: `MileagePlus\nEarn 12,000 more PQP to reach Premier Gold\n88,000 miles`,
    expect: { program: 'united', balance: 88000, progress: null } },
  { name: 'Hilton: "points remaining" is still the balance', text: `Hilton Honors\nSilver\n26,948 points remaining`,
    expect: { program: 'hilton', balance: 26948, tier: 'Silver' } },
  { name: 'Chase: Sapphire page that names United', text: `Sapphire Reserve\n148,920 points\nTransfer to United MileagePlus 1:1`,
    expect: { program: 'chase', balance: 148920 } },

  // ---------- Audit: tiles, offers, co-brand cards, expiry dates, OCR slips ----------
  // Value-above-caption tiles: the caption under one tile isn't the next tile's label.
  { name: 'Audit 1a: Flying Blue tiles, XP under its number', text: `Flying Blue\nGold\n78,450\nMiles\n182\nXP\nStatus valid until 31/03/2027`,
    expect: { program: 'flyingblue', balance: 78450 } },
  { name: 'Audit 1b: Emirates tiles, tier miles', text: `Emirates Skywards\nGold\n40,120\nSkywards Miles\n28,000\nTier Miles\nTier valid until 31 Jan 2027`,
    expect: { program: 'emirates', balance: 40120 } },
  { name: 'Audit 1c: BA tiles, tier points', text: `British Airways Club\nSilver\n96,320\nAvios\n1,840\nTier Points`,
    expect: { program: 'ba', balance: 96320 } },
  { name: 'Audit 1d: KrisFlyer tiles, elite miles', text: `KrisFlyer\nElite Gold\n88,000\nKrisFlyer miles\n32,500\nElite miles`,
    expect: { program: 'singapore', balance: 88000 } },
  { name: 'Audit 1e: Accor tiles, status points', text: `ALL Accor\nGold\n12,400\nReward points\n3,250\nStatus points\nStatus valid until 31/12/2026`,
    expect: { program: 'accor', balance: 12400 } },
  { name: 'Audit 1f: Virgin tiles, tier points', text: `Flying Club\nSilver\n120,450\nVirgin Points\n450\nTier points`,
    expect: { program: 'virgin', balance: 120450 } },
  { name: 'Audit 1g: Qatar tiles, Qpoints', text: `Privilege Club\nGold\n154,300\nAvios\n640\nQpoints`,
    expect: { program: 'qatar', balance: 154300 } },
  { name: 'Audit 1h: United tiles, PQP and PQF', text: `MileagePlus\nPremier Gold\n64,018\nMiles\n7,850\nPQP\n12\nPQF`,
    expect: { program: 'united', balance: 64018 } },
  { name: 'Audit 1i: Flying Blue tiles read row by row', text: `Flying Blue\nGold\n78,450 182\nMiles XP`,
    expect: { program: 'flyingblue', balance: 78450 } },
  { name: 'Audit 1j: Hilton pending points', text: `Hilton Honors\nDiamond\n302,118 Points\n4,250 Points pending`,
    expect: { program: 'hilton', balance: 302118 } },
  // Counts take their own label's number, not the next tile's or a neighbouring label's.
  { name: 'Audit 2a: Hilton tiles, nights and stays', text: `Hilton Honors\nDiamond\n302,118\nPoints\n61\nNights\n24\nStays`,
    expect: { program: 'hilton', progress: 61, alt: 24 } },
  { name: 'Audit 2b: Hyatt tiles, night credits and base points', text: `World of Hyatt\nExplorist\n45,120\nCurrent Points\n31\nQualifying Night Credits\n18,402\nBase Points`,
    expect: { program: 'hyatt', progress: 31, alt: 18402 } },
  { name: 'Audit 2c: IHG tiles, nights and qualifying points', text: `IHG One Rewards\nDiamond Elite\n26,948\nPoints\n44\nQualifying nights\n61,200\nQualifying points`,
    expect: { program: 'ihg', progress: 44, alt: 61200 } },
  { name: 'Audit 2d: Hilton, two labels on one line (label first)', text: `Hilton Honors\nDiamond\n302,118 Points\nNights 61 Stays 24`,
    expect: { program: 'hilton', progress: 61, alt: 24 } },
  { name: 'Audit 2e: Hilton, two labels on one line (number first)', text: `Hilton Honors\nDiamond\n302,118 Points\n61 Nights 24 Stays`,
    expect: { program: 'hilton', progress: 61, alt: 24 } },
  { name: 'Audit 2f: United, PQF and PQP on one line', text: `MileagePlus\nPremier Gold\n64,018 miles\nPQF 31 / 45 PQP 12,450 / 18,000`,
    expect: { program: 'united', progress: 12450, alt: 31 } },
  { name: 'Audit 2g: Hyatt, nights and base points on one line', text: `World of Hyatt\nExplorist\n45,120 points\nNights 31 Base points 18,402`,
    expect: { program: 'hyatt', progress: 31, alt: 18402 } },
  // A tier-points or status-points caption above a number doesn't earn the balance bonus.
  { name: 'Audit 3a: BA, tier points caption first', text: `The British Airways Club\nGold\nTier Points\n1,840 / 3,500\nAvios\n96,320`,
    expect: { program: 'ba', balance: 96320 } },
  { name: 'Audit 3b: Accor, status points caption first', text: `ALL - Accor Live Limitless\nSilver\nStatus points\n3,250\nReward points\n12,400`,
    expect: { program: 'accor', balance: 12400 } },
  // Reward prices and offers aren't the balance.
  { name: 'Audit 4a: Hilton, "rooms from 5,000 Points"', text: `Hilton Honors\nGold\n34,500\nPoints\n18\nNights\nStandard rooms from 5,000 Points`,
    expect: { program: 'hilton', balance: 34500 } },
  { name: 'Audit 4b: Marriott, "Earn 500 points"', text: `Marriott Bonvoy\nPlatinum Elite\n98,410\nPoints\n51\nNights\nEarn 500 points with Starbucks`,
    expect: { program: 'marriott', balance: 98410 } },
  { name: 'Audit 4c: Marriott, refer a friend', text: `Marriott Bonvoy\nGold Elite\n48,320\nPoints\n32\nNights\nRefer a friend: earn 10,000 points`,
    expect: { program: 'marriott', balance: 48320 } },
  { name: 'Audit 4d: Capital One, refer a friend', text: `Capital One\nVenture X\n75,123\nmiles\n= $751.23 in travel\nEarn 10,000 miles when you refer a friend`,
    expect: { program: 'capitalone', balance: 75123 } },
  // A co-brand card's name doesn't make the screen the issuer's.
  { name: 'Audit 5a: Delta app showing its Amex card', text: `SkyMiles\nGold Medallion\nDelta SkyMiles Reserve American Express Card\n84,250 miles\nMQDs $11,240`,
    expect: { program: 'delta', tier: 'Gold Medallion', balance: 84250, mqd: 11240 } },
  { name: 'Audit 5b: Marriott app showing its Amex card', text: `Marriott Bonvoy\nPlatinum Elite\nMarriott Bonvoy Brilliant American Express Card\n98,410 points\nNights this year 51`,
    expect: { program: 'marriott', tier: 'Platinum Elite', balance: 98410, progress: 51 } },
  { name: 'Audit 5c: Amex app showing a Delta card', text: `AMERICAN EXPRESS\nDelta SkyMiles Gold Card\nSkyMiles\n84,250`,
    expect: { program: 'delta', balance: 84250 } },
  // A points or miles expiry date isn't when status ends.
  { name: 'Audit 6a: KrisFlyer, miles expiring', text: `KrisFlyer\nElite Silver\n88,000 KrisFlyer miles\n5,200 miles expiring on 30 Nov 2026`,
    expect: { program: 'singapore', exp: null } },
  { name: 'Audit 6b: Emirates, miles expiring then tier date', text: `Emirates Skywards\nGold\nSkywards Miles 40,120\n3,200 Miles expiring on 31 Dec 2026\nTier valid until 31 Jan 2027`,
    expect: { program: 'emirates', exp: '2027-01-31' } },
  { name: 'Audit 6c: Accor, points expiring then status date', text: `ALL Accor\nSilver\n12,400 Reward points\nPoints expiring on 31/03/2027\nStatus valid until 31/12/2026`,
    expect: { program: 'accor', exp: '2026-12-31' } },
  { name: 'Audit 6d: Choice, points expiring only', text: `Choice Privileges\nPlatinum\n61,200 points\nPoints expiring: 08/14/2027`,
    expect: { program: 'choice', exp: null } },
  // Digit misreads in short counts, and space-grouped thousands after or under a label.
  { name: 'Audit 7a: Hilton, "l8" nights', text: `Hilton Honors\nGold\nPoints 34,500\nNights l8`,
    expect: { program: 'hilton', progress: 18 } },
  { name: 'Audit 7b: Hilton, "2O" nights', text: `Hilton Honors\nGold\nPoints 34,500\nNights 2O`,
    expect: { program: 'hilton', progress: 20 } },
  { name: 'Audit 7c: United, "l4" PQF', text: `MileagePlus\nPremier Gold\n64,018 miles\nPQP 12,450\nPQF l4`,
    expect: { program: 'united', alt: 14 } },
  { name: 'Audit 7d: Hilton, "l9" nights and stays on one line', text: `Hilton Honors\n» Diamond\n302,118 Points\nNights l9 · Stays 7`,
    expect: { program: 'hilton', progress: 19, alt: 7 } },
  { name: 'Audit 7e: BA, "Avios 96 320"', text: `British Airways\nBronze\nAvios 96 320`,
    expect: { program: 'ba', balance: 96320 } },
  { name: 'Audit 7f: Flying Blue, "Miles 78 450"', text: `Flying Blue\nGold\nMiles 78 450\nXP 182`,
    expect: { program: 'flyingblue', balance: 78450 } },
  { name: 'Audit 7g: Flying Blue, "78 450" under its caption', text: `Flying Blue\nSilver\nMiles\n78 450\nXP\n182`,
    expect: { program: 'flyingblue', balance: 78450 } },
  { name: 'Audit 7h: Accor, "12 400" under its caption', text: `ALL Accor\nGold\nPoints Rewards\n12 400`,
    expect: { program: 'accor', balance: 12400 } },
  // Companion Pass progress isn't A-List progress.
  { name: 'Audit 8a: Southwest, Companion Pass lines first', text: `Southwest Rapid Rewards\nA-List\n31,200 points\nCompanion Pass qualifying flights 62 of 100\nCompanion Pass qualifying points 98,000 of 135,000\nTier qualifying flights 14 of 20\nTier qualifying points 22,400 of 35,000`,
    expect: { program: 'southwest', progress: 22400, alt: 14 } },
  { name: 'Audit 8b: Southwest, Companion Pass section first', text: `Southwest Rapid Rewards\nA-List\n31,200 points\nCompanion Pass progress\n62 of 100 qualifying flights\n98,000 of 135,000 qualifying points\nA-List progress\n14 of 20 qualifying flights\n22,400 of 35,000 tier qualifying points`,
    expect: { program: 'southwest', progress: 22400, alt: 14 } },
  // A header with a unit word ("SkyMiles", "My Points") above value-first tiles is a header, not the first caption.
  { name: 'Audit 9a: Delta, SkyMiles header above value-first tiles', text: `SkyMiles\n84,250\nMiles\n$11,240\nMQDs`,
    expect: { program: 'delta', balance: 84250, mqd: 11240 } },
  { name: 'Audit 9b: Delta, "Delta SkyMiles" header above value-first tiles', text: `Delta SkyMiles\n84,250\nMiles\n$11,240\nMQDs`,
    expect: { program: 'delta', balance: 84250, mqd: 11240 } },
  { name: 'Audit 9c: Hyatt, status bar and "My Points" header above tiles', text: `9:41 5G 72%\nWorld of Hyatt\nMy Points\n45,120\nPoints\n312\nBase points`,
    expect: { program: 'hyatt', balance: 45120, alt: 312 } },
  { name: 'Audit 9d: Southwest, "Rapid Rewards points" header above tiles', text: `Rapid Rewards points\n12,870\nPoints\n18,200\nTier qualifying points`,
    expect: { program: 'southwest', balance: 12870, progress: 18200 } },
  { name: 'Audit 9e: United, "Miles & status" header above tiles', text: `MileagePlus\nMiles & status\n64,018\nMiles\n7,850\nPQP\n12\nPQF`,
    expect: { program: 'united', balance: 64018, progress: 7850, alt: 12 } },
  // A program-name caption over the balance reads caption-first, even with no unit word in it.
  { name: 'Audit 9f: Chase, "Ultimate Rewards" over the balance, pending below', text: `Chase\nUltimate Rewards\n84,210\nPending points\n1,250`,
    expect: { program: 'chase', balance: 84210 } },
  { name: 'Audit 9g: Alaska, "Atmos Rewards" over the balance', text: `Atmos Rewards\n63,005\nStatus points\n24,100`,
    expect: { program: 'alaska', balance: 63005, progress: 24100 } },
  // "Preferred" isn't "refer a friend".
  { name: 'Audit 10a: Southwest, "A-List Preferred" merged with the balance', text: `Rapid Rewards\nA-List Preferred 45,980 points\nTier qualifying points 70,500`,
    expect: { program: 'southwest', balance: 45980, tier: 'A-List Preferred', progress: 70500 } },
  { name: 'Audit 10b: Chase, "Sapphire Preferred" merged with the balance', text: `Chase Ultimate Rewards\nSapphire Preferred 120,345 points`,
    expect: { program: 'chase', balance: 120345 } },
  { name: 'Audit 10c: Bank of America, "Preferred Rewards" merged with the balance', text: `Bank of America\nPreferred Rewards Gold 18,400 points`,
    expect: { program: 'bofa', balance: 18400 } },
  // A merged line's level name, status date or other column isn't the balance's caption.
  { name: 'Audit 10d: Hilton, status date merged with points', text: `Hilton Honors\nGold through 03/31/2028 Points 52,000\nNights 27`,
    expect: { program: 'hilton', balance: 52000, tier: 'Gold', exp: '2028-03-31', progress: 27 } },
  { name: 'Audit 10e: Hyatt, "Exp" date merged with points', text: `World of Hyatt\nExplorist Exp 12/31/27 41,200 points`,
    expect: { program: 'hyatt', balance: 41200, tier: 'Explorist', exp: '2027-12-31' } },
  { name: 'Audit 10f: Marriott, "Gold Elite" merged with "Points 48,320"', text: `MARRIOTT BONVOY\nGold Elite Points 48,320\nNights 32`,
    expect: { program: 'marriott', balance: 48320, tier: 'Gold Elite', progress: 32 } },
  { name: 'Audit 10g: BA, "Silver tier" merged with Avios', text: `British Airways Club\nSilver tier Avios 96,320`,
    expect: { program: 'ba', balance: 96320, tier: 'Silver' } },
  { name: 'Audit 10h: Delta, miles merged with a "Book a flight" tab', text: `Delta\nGold Medallion\nMiles 84,250 Book a flight\nMQDs $11,240`,
    expect: { program: 'delta', balance: 84250, tier: 'Gold Medallion', mqd: 11240 } },
  { name: 'Audit 10i: Chase, "points to use on flights and hotels"', text: `Chase Ultimate Rewards\n120,345 points to use on flights and hotels`,
    expect: { program: 'chase', balance: 120345 } },
  { name: 'Audit 10j: Hilton, points merged with a "My Stays" tab', text: `Hilton Honors\nGold\nPoints 34,500 My Stays`,
    expect: { program: 'hilton', balance: 34500, tier: 'Gold' } },
  // An offer's end date and the numbers in it aren't status or counts.
  { name: 'Audit 11a: Marriott, elite-night promo date before the status date', text: `Marriott Bonvoy\nPlatinum Elite\nDouble Elite Night Credits through Dec 31, 2026\n98,410 points\nStatus valid until Feb 28, 2028`,
    expect: { program: 'marriott', balance: 98410, exp: '2028-02-28' } },
  { name: 'Audit 11b: Hilton, stays promo with a date, then tiles', text: `Hilton Honors\nDiamond\nEarn 3X Points on stays through Dec 31, 2026\n142,700\nPoints\nNights\n57\nStays\n21`,
    expect: { program: 'hilton', balance: 142700, tier: 'Diamond', progress: 57, alt: 21, exp: null } },
  { name: 'Audit 11c: Amex, "from 1,000 points" price below the balance', text: `Membership Rewards\nPoints available from all cards: 212,480\nShop with points from 1,000 points`,
    expect: { program: 'amex', balance: 212480 } },
  { name: 'Audit 11d: Citi, with an AAdvantage co-brand card offer', text: `Citi\nThankYou Points\n68,940\nCiti Strata Premier Card\nApply for the Citi AAdvantage Executive World Elite Mastercard\nEarn 70,000 American Airlines AAdvantage bonus miles`,
    expect: { program: 'citi', balance: 68940 } },
  { name: 'Audit 11e: Hilton, nights and stays "from Jan 1"', text: `Hilton Honors\nGold\nPoints 45,210\nNights stayed from Jan 1: 22\nStays from Jan 1: 9`,
    expect: { program: 'hilton', balance: 45210, progress: 22, alt: 9 } },
  // Space-grouped thousands under a two-word caption, and space-grouped member numbers.
  { name: 'Audit 12a: Virgin, "48 215" above "Virgin Points"', text: `Virgin Atlantic Flying Club\nGold\n48 215\nVirgin Points\n612\nTier points`,
    expect: { program: 'virgin', balance: 48215, tier: 'Gold' } },
  { name: 'Audit 12b: Hilton, member number "123 456 789" above a Points tile', text: `Hilton Honors\nGold\nMember number\n123 456 789\nPoints\n45 210`,
    expect: { program: 'hilton', balance: 45210, member: '123456789' } },
  { name: 'Audit 12c: Hilton, member number "123 456 789" then Points on one line', text: `Hilton Honors Gold\nMember # 123 456 789 Points 45 210`,
    expect: { program: 'hilton', balance: 45210, member: '123456789' } },
  { name: 'Audit 12d: Delta, member number under a "SkyMiles Number" caption', text: `Delta SkyMiles\nSilver Medallion\nSkyMiles Number\n9123 456 789\nMiles\n45 210`,
    expect: { program: 'delta', balance: 45210, member: '9123456789', tier: 'Silver Medallion' } },

  // ---------- More layouts for the same rules ----------
  // Value-above-caption tiles, other programs.
  { name: 'Marriott tiles, value above caption', text: `Marriott Bonvoy\nTitanium Elite\n250,145\nPoints\n76\nNights this year\nMember since 2014`,
    expect: { program: 'marriott', balance: 250145, tier: 'Titanium Elite', progress: 76 } },
  { name: 'Alaska tiles, status points under its number', text: `Atmos Rewards\nAtmos Platinum\n38,700\nPoints\n43,500\nStatus points`,
    expect: { program: 'alaska', balance: 38700, tier: 'Platinum', progress: 43500 } },
  { name: 'Aeroplan tiles, SQC under its number', text: `Aeroplan\n50K\n112,400\nPoints\n41,200\nSQC`,
    expect: { program: 'aeroplan', balance: 112400, progress: 41200 } },
  { name: 'Delta tiles, MQDs under a dollar value', text: `SkyMiles\nGold Medallion\n84,250\nMiles\n$11,240\nMQDs`,
    expect: { program: 'delta', balance: 84250, tier: 'Gold Medallion', mqd: 11240 } },
  // Caption-above-value tiles, including a trailing button line.
  { name: 'Hilton tiles, caption above value', text: `Hilton Honors\nGold\nPoints\n34,500\nNights\n18\nStays\n7`,
    expect: { program: 'hilton', balance: 34500, progress: 18, alt: 7 } },
  { name: 'Hyatt tiles, caption above value, button below', text: `World of Hyatt\nGlobalist\nCurrent Points\n45,120\nQualifying Night Credits\n64\nBase Points\n102,300\nView activity`,
    expect: { program: 'hyatt', balance: 45120, tier: 'Globalist', progress: 64, alt: 102300 } },
  { name: 'BA tiles, caption above, lifetime tier points last', text: `British Airways Club\nGold\nAvios\n96,320\nTier Points\n1,840\nLifetime Tier Points\n24,000`,
    expect: { program: 'ba', balance: 96320, tier: 'Gold' } },
  // Tiles read row by row: one caption line split across the values.
  { name: 'Hilton tiles row by row, three columns', text: `Hilton Honors\nDiamond\n302,118 61 24\nPoints Nights Stays`,
    expect: { program: 'hilton', balance: 302118, tier: 'Diamond', progress: 61, alt: 24 } },
  { name: 'United tiles row by row', text: `MileagePlus\nPremier Platinum\n120,500 18,400 22\nMiles PQP PQF`,
    expect: { program: 'united', balance: 120500, tier: 'Premier Platinum', progress: 18400, alt: 22 } },
  { name: 'IHG tiles row by row, captions above', text: `IHG One Rewards\nPlatinum Elite\nPoints Qualifying nights\n26,948 22`,
    expect: { program: 'ihg', balance: 26948, tier: 'Platinum Elite', progress: 22 } },
  { name: 'Accor tiles row by row, two-word captions', text: `ALL Accor\nPlatinum\n12,400 3,250\nReward points Status points`,
    expect: { program: 'accor', balance: 12400, tier: 'Platinum' } },
  // Two labels on one line.
  { name: 'Marriott: nights and lifetime nights on one line', text: `Marriott Bonvoy\nPlatinum Elite\n98,410 points\nNights this year 51 Lifetime nights 412`,
    expect: { program: 'marriott', balance: 98410, progress: 51 } },
  { name: 'Hyatt: number-first nights and base points', text: `World of Hyatt\nGlobalist\n45,120 points\n64 nights 102,300 base points`,
    expect: { program: 'hyatt', balance: 45120, progress: 64, alt: 102300 } },
  // Prices, offers and pending points aren't the balance (or a count).
  { name: 'Hyatt: free nights "starting at" a price', text: `World of Hyatt\nExplorist\nFree nights starting at 3,500 points\n45,120 points\nQualifying night credits 31`,
    expect: { program: 'hyatt', balance: 45120, progress: 31 } },
  { name: 'United: award flights "as low as" a price', text: `MileagePlus\nPremier Silver\nAward flights as low as 5,000 miles\n88,000 miles\nPQP 7,200`,
    expect: { program: 'united', balance: 88000, progress: 7200, alt: null } },
  { name: 'Marriott: pending points above the balance', text: `Marriott Bonvoy\nGold Elite\nPending points 2,400\n48,320 points\nNights this year 32`,
    expect: { program: 'marriott', balance: 48320, progress: 32 } },
  // Co-brand cards in an issuer's app, and an issuer's own card.
  { name: 'Amex app showing a Hilton card', text: `American Express\nHilton Honors Aspire Card\nHilton Honors\n150,000 points`,
    expect: { program: 'hilton', balance: 150000 } },
  { name: 'Chase app showing a United card', text: `Chase\nUnited Explorer Card\nMileagePlus miles\n45,000`,
    expect: { program: 'united', balance: 45000 } },
  { name: 'Amex app, its own Platinum Card', text: `American Express\nPlatinum Card\nMembership Rewards\n88,050 points`,
    expect: { program: 'amex', balance: 88050 } },
  // Points expiry vs status end dates.
  { name: 'Hyatt: points expiring, then status through', text: `World of Hyatt\nGlobalist\n45,120 points\n2,000 points expiring Dec 31, 2026\nGlobalist through Feb 28, 2028`,
    expect: { program: 'hyatt', balance: 45120, tier: 'Globalist', exp: '2028-02-28' } },
  { name: 'Marriott: points expiration date, then elite through', text: `Marriott Bonvoy\nPlatinum Elite\n98,410 points\nPoints expiration date: 03/31/2028\nPlatinum Elite through Feb 28, 2028`,
    expect: { program: 'marriott', balance: 98410, exp: '2028-02-28' } },
  // OCR digit slips and space-grouped thousands.
  { name: 'Hilton: "3l" nights and "l2" stays', text: `Hilton Honors\nGold\nPoints 34,500\nNights 3l\nStays l2`,
    expect: { program: 'hilton', balance: 34500, progress: 31, alt: 12 } },
  { name: 'IHG: "2O" qualifying nights, member number intact', text: `IHG One Rewards\nPlatinum Elite\n26,948 pts\nQualifying nights 2O\nMember 123456789`,
    expect: { program: 'ihg', balance: 26948, progress: 20, member: '123456789' } },
  { name: 'Virgin: "Virgin Points 120 450"', text: `Virgin Atlantic\nFlying Club Gold\nVirgin Points 120 450\nTier points 450`,
    expect: { program: 'virgin', balance: 120450, tier: 'Gold' } },
  { name: 'Iberia: spaced thousands under captions', text: `Iberia Club\nOro\nAvios\n45 200\nElite points\n2 600`,
    expect: { program: 'iberia', balance: 45200, tier: 'Oro' } },
  // Companion Pass tiles under their own heading.
  { name: 'Southwest tiles: Companion Pass then A-List', text: `Rapid Rewards\nA-List\n31,200\nPoints\nCompanion Pass\n62\nQualifying flights\nA-List progress\n14\nQualifying flights`,
    expect: { program: 'southwest', balance: 31200, tier: 'A-List', alt: 14 } },

  // ---------- Probe round 1 ----------
  // A nav or tab row under a "Points N" line is not the balance's caption.
  { name: 'Probe S4: Southwest promo and price above the balance', text: `Southwest\nEarn 50,000 points with the Rapid Rewards Priority Card\nFlights from 1,200 points\nRapid Rewards\nPoints 9,860\nBook Check in Flight status`,
    expect: { program: 'southwest', balance: 9860 } },
  { name: 'Probe S4-min: Southwest nav row under the balance', text: `Southwest\nRapid Rewards\nPoints 9,860\nBook Flight status Trips`,
    expect: { program: 'southwest', balance: 9860 } },
  { name: 'Probe S4-min: Delta nav row under the balance', text: `SkyMiles\nMiles 52,118\nFlights Trips Today`,
    expect: { program: 'delta', balance: 52118 } },
  { name: 'Probe S4-min: United nav row under the balance', text: `MileagePlus\nMiles 52,118\nFlight status`,
    expect: { program: 'united', balance: 52118 } },
  { name: 'Probe S4-min: Marriott tab under the balance', text: `Marriott Bonvoy\nPoints 52,118\nMy Stays`,
    expect: { program: 'marriott', balance: 52118 } },
  // Member numbers after a program name that is itself a label word.
  { name: 'Probe S3: Southwest merged dot line with member', text: `Rapid Rewards® | Member # 20123456789\nAvailable points 18,240 · Tier points 12,600 · Flights 6`,
    expect: { program: 'southwest', member: '20123456789', balance: 18240, progress: 12600, alt: 6 } },
  { name: 'Probe S3b: Hilton Honors | Member #', text: `Hilton Honors | Member # 123456789\nGold\nPoints 34,500`,
    expect: { program: 'hilton', member: '123456789', balance: 34500 } },
  { name: 'Probe J2: JetBlue merged value line, TrueBlue #', text: `TrueBlue | Mosaic 1\n18,450 64\nPoints Tiles\nTrueBlue # 3012345678`,
    expect: { program: 'jetblue', balance: 18450, tier: 'Mosaic 1', member: '3012345678' } },
  // Card last 4 ("(...4417)", "...7731", "•••• 1009") on a line of their own is never the balance.
  { name: 'Probe 06: IHG Premier card in Chase app', text: `CHASE\nIHG One Rewards Premier Credit Card\n(...4417)\nYour IHG One Rewards points\n61,250\nPlatinum Elite\nAnniversary Free Night expires 09/30/2027\nIHG One Rewards Member 123456789`,
    expect: { program: 'ihg', balance: 61250, tier: 'Platinum Elite', exp: null, progress: null, member: '123456789' } },
  { name: 'Probe 06b: "IHG One Rewards Member" number', text: `IHG One Rewards Member 123456789`,
    expect: { member: '123456789' } },
  { name: 'Probe 21: Citi AAdvantage Executive', text: `Citi\nCiti® / AAdvantage® Executive World Elite Mastercard®\n...7731\nAAdvantage® miles\n78,450\nLoyalty Points 41,200`,
    expect: { program: 'american', balance: 78450, progress: 41200 } },
  { name: 'Probe 02: Marriott Brilliant in Amex app', text: `Amex\nMarriott Bonvoy Brilliant® American Express® Card\n•••• 1009\nMarriott Bonvoy Points\n74,210\nEarn 6X points at hotels in the Marriott Bonvoy portfolio\nPlatinum Elite\nElite Night Credits 38`,
    expect: { program: 'marriott', balance: 74210, tier: 'Platinum Elite', progress: 38 } },
  // A free night certificate's expiry is not the status end date.
  { name: 'Probe 17: Marriott Boundless in Chase app, FNA expiry', text: `CHASE\nMarriott Bonvoy Boundless® Credit Card (...7310)\nPoints are earned in your Marriott Bonvoy account\nMarriott Bonvoy points 63,018\nFree Night Award expires 06/30/2027`,
    expect: { program: 'marriott', balance: 63018, exp: null, progress: null } },
  // A program name holding a level's word ("Accor Live Limitless", "Virgin Red") is not the level.
  { name: 'Probe 13: Accor euro value + status expires on', text: `Accor Live Limitless\nPlatinum\n2,640 Reward points (= €52)\nStatus points 14,200 / 14,000\nStatus expires on 28/02/2028`,
    expect: { program: 'accor', balance: 2640, tier: 'Platinum', exp: '2028-02-28' } },
  { name: 'Probe: Virgin Red app with Flying Club Gold', text: `Virgin Red\nVirgin Points 23,400\nFlying Club Gold`,
    expect: { program: 'virgin', balance: 23400, tier: 'Gold' } },
  // Card-earned PQP is only part of the total; the MileagePlus number is not a card's digits.
  { name: 'Probe 30: Chase United Explorer, PQP from card only', text: `CHASE\nUnited℠ Explorer Card (...1180)\nUnited MileagePlus® miles\n45,600\nPremier qualifying points earned with card: 1,000\nMileagePlus #: QW482917`,
    expect: { program: 'united', balance: 45600, progress: null, member: 'QW482917' } },
  // Dates: "valid till", and a month/year status card date (its last day).
  { name: 'Probe: KrisFlyer PPS, valid till', text: `KrisFlyer\nPPS Club\nKrisFlyer miles 145,200\nPPS Value 28,400 / 25,000\nElite miles 52,000\nMembership valid till 31 Jan 2028`,
    expect: { program: 'singapore', balance: 145200, tier: 'PPS Club', exp: '2028-01-31' } },
  { name: 'Probe: Lufthansa new points system, MM/YYYY', text: `Miles & More\nFrequent Traveller\nAward miles 34,560\nPoints 520\nQualifying Points 410\nHON Circle Points 0\nStatus valid until 02/2028`,
    expect: { program: 'lufthansa', balance: 34560, tier: 'Frequent Traveller', exp: '2028-02-29' } },
  // Turkish: Status Miles are a count; levels are shown as "Elite Card".
  { name: 'Probe: Turkish status miles before total miles', text: `Miles&Smiles\nClassic Plus\nStatus Miles 26,500 / 40,000\nTotal Miles 48,220\nCard valid until 31.03.2027`,
    expect: { program: 'turkish', balance: 48220, tier: 'Classic Plus', exp: '2027-03-31' } },
  { name: 'Probe: Turkish "Elite Card" status only', text: `Miles&Smiles\nElite Card\nValid until 31.07.2027\nMember no. TK 123456789`,
    expect: { program: 'turkish', tier: 'Elite', balance: null, exp: '2027-07-31', member: 'TK123456789' } },

  // ---------- Probe round 2 ----------
  // A bare "Valid through" line belongs to the heading just above it: a level's, or a Companion Pass's (not status).
  // Lounge memberships and companion fares or passes have their own end dates.
  { name: 'R2 Delta Sky Club date vs status', text: `Profile\nDelta Sky Club® Membership valid through May 31, 2027\nGold Medallion\nValid through Jan 31, 2027\nSkyMiles\n84,250`,
    expect: { program: 'delta', balance: 84250, tier: 'Gold Medallion', exp: '2027-01-31' } },
  { name: 'R2 Southwest companion pass date', text: `Rapid Rewards\nA-List\nCompanion Pass® holder\nValid through 12/31/2027\nAvailable points 45,980\nTier qualifying points 40,100`,
    expect: { program: 'southwest', balance: 45980, tier: 'A-List', exp: null, progress: 40100 } },
  { name: 'R2 Alaska companion fare date', text: `Atmos Rewards\nAtmos Gold\nAvailable points\n38,700\nStatus points\n43,500 of 80,000 to Platinum\nCompanion Fare expires Dec 31, 2026`,
    expect: { program: 'alaska', balance: 38700, tier: 'Gold', exp: null, progress: 43500 } },
  // Value-first tiles after a level or card name: a "Pending" or "Lifetime" caption names something else.
  { name: 'R2 Hilton: value-first tiles, pending tile last', text: `Hilton Honors\nGold\n82,115\nPoints\n4,200\nPending points`,
    expect: { program: 'hilton', balance: 82115, tier: 'Gold' } },
  { name: 'R2 Capital One: value-first tiles, pending tile last', text: `Capital One\nVenture X\n142,880\nMiles\n5,000\nPending miles`,
    expect: { program: 'capitalone', balance: 142880 } },
  { name: 'R2 BA value-first tiles ending with Lifetime Tier Points', text: `British Airways Club\nSilver\n96 320\nAvios\n1 120\nTier Points\n12 400\nLifetime Tier Points`,
    expect: { program: 'ba', balance: 96320, tier: 'Silver' } },
  { name: 'R2 BA value-first tiles, commas, Lifetime Tier Points', text: `British Airways Club\nSilver\n96,320\nAvios\n1,120\nTier Points\n12,400\nLifetime Tier Points`,
    expect: { program: 'ba', balance: 96320, tier: 'Silver' } },
  // Space-grouped thousands with a word before the unit ("2 450 Reward points", "1 204 553 award miles").
  { name: 'R2 Accor: spaced balance before "Reward points", 16-digit card no.', text: `ALL - Accor Live Limitless\nSilver\n2 450 Reward points\n= €49 to spend\nStatus until 28/02/2028\nMember no. 3081 0312 3456 7890`,
    expect: { program: 'accor', balance: 2450, tier: 'Silver', exp: '2028-02-28', member: '3081031234567890' } },
  { name: 'R2 Miles & More HON: spaced million balance before award miles', text: `Miles & More\nHON Circle\n1 204 553 award miles\nHON Circle Points 6,200\nStatus valid until 28 Feb 2029`,
    expect: { program: 'lufthansa', balance: 1204553, tier: 'HON Circle', exp: '2029-02-28' } },
  // What's still needed for a level ("needed for Gold", "required for Elite") is a target, not the status.
  { name: 'R2 Virgin: "Tier points needed for Gold"', text: `Virgin Atlantic Flying Club\nSilver\nVirgin Points\n48 900\nTier Points\n215\nTier points needed for Gold: 185\nSilver until 30/09/2027`,
    expect: { program: 'virgin', balance: 48900, tier: 'Silver', exp: '2027-09-30' } },
  { name: 'R2 Turkish: "Status miles required for Elite"', text: `Miles&Smiles\nClassic Plus\nMiles 23,500\nStatus miles 18,200\nStatus miles required for Elite 21,800`,
    expect: { program: 'turkish', balance: 23500, tier: 'Classic Plus' } },
  // A "+1 240 Miles" credit in recent activity is a transaction, not the balance.
  { name: 'R2 Flying Blue: recent-activity credit above the Miles tile', text: `Flying Blue\nGold\nLatest activity: AF1234 Paris\n+1 240 Miles\nMiles\n52 300\nXP\n188`,
    expect: { program: 'flyingblue', balance: 52300, tier: 'Gold' } },

  // ---------- Probe round 3
  // A Companion Pass heading with its own end date is a held pass, not a progress section; a status count line ends it.
  { name: 'R3 Southwest CP valid through later', text: `Rapid Rewards\nA-List Preferred\nStatus valid through 12/31/2027\nCompanion Pass\nValid through 12/31/2028\nPoints 66,040\nTier qualifying points 80,200\nFlights 44`,
    expect: { program: 'southwest', balance: 66040, tier: 'A-List Preferred', progress: 80200, alt: 44, exp: '2027-12-31' } },
  // Merged lines where every amount has its unit right after it ("61,400 Miles $16,250 MQDs"); short forms "Tier pts", "status pts".
  { name: 'R3 Delta merged line', text: `SkyMiles 61,400 Miles | $16,250 MQDs | Platinum Medallion\nMedallion® Status through 1/31/2027`,
    expect: { program: 'delta', balance: 61400, tier: 'Platinum Medallion', mqd: 16250, exp: '2027-01-31' } },
  { name: 'R3 Southwest merged line', text: `Rapid Rewards® | A-List Preferred | 112,050 pts | Tier pts 71,300 | Flights 41`,
    expect: { program: 'southwest', balance: 112050, tier: 'A-List Preferred', progress: 71300, alt: 41 } },
  { name: 'R3 Southwest "Tier pts" on its own line', text: `Rapid Rewards\nA-List\nAvailable points 45,980\nTier pts 71,300\nFlights 12`,
    expect: { program: 'southwest', balance: 45980, progress: 71300, alt: 12 } },
  { name: 'R3 Alaska merged line', text: `Atmos Rewards · Gold · 31,775 pts · 41,250 status pts\nHawaiian Airlines & Alaska Airlines`,
    expect: { program: 'alaska', balance: 31775, tier: 'Gold', progress: 41250 } },
  { name: 'R3 Alaska "status pts" on its own line', text: `Atmos Rewards\nAtmos Gold\n38,700 points\nStatus pts 43,500`,
    expect: { program: 'alaska', balance: 38700, tier: 'Gold', progress: 43500 } },
  // A Lifetime Miles tile is not the balance.
  { name: 'R3 Delta Diamond lifetime + target', text: `SkyMiles\nDiamond Medallion®\n2027 Medallion Status\nMQDs\n$31,882\n$28,000 Diamond\nLifetime Miles\n1,204,331\nAvailable Miles\n392,410`,
    expect: { program: 'delta', balance: 392410, mqd: 31882, tier: 'Diamond Medallion' } },
  // Prices and conversions ("Buy points: 10,000 pts for $135", "2 000 points = €40 off") aren't the balance; "3 200 Reward points" is.
  { name: 'R3-07 IHG: Premier card, buy-points price line', text: `IHG One Rewards\nDiamond Elite\nMember through 12/31/2027\n182,400\npts\nIHG One Rewards Premier Credit Card\nGet 4th reward night free\nBuy points: 10,000 pts for $135\nQualifying nights 55`,
    expect: { program: 'ihg', balance: 182400, progress: 55 } },
  { name: 'R3-14 Accor: spaced thousands and a points-to-euro conversion', text: `ALL Accor Live Limitless\nSilver\n3 200 Reward points\n2 000 points = €40 off your stay\nStatus points 2,450 / 3,000\nValid until 31/12/2026`,
    expect: { program: 'accor', balance: 3200, tier: 'Silver', exp: '2026-12-31' } },
  { name: 'R3-14b Accor: commas, conversion line', text: `ALL Accor Live Limitless\nSilver\n3,200 Reward points\n2,000 points = €40 off your stay`,
    expect: { program: 'accor', balance: 3200 } },
  // A transfer screen's "points available to transfer" is the balance; the minimum transfer is not.
  { name: 'R3-18 Chase transfer screen: balance sits on a transfer line', text: `Ultimate Rewards\nTransfer points\nWorld of Hyatt\n1:1 transfer ratio\nYou have 92,610 points available to transfer\nMinimum transfer 1,000 points`,
    expect: { program: 'chase', balance: 92610 } },
  // A free night award line ("Category 1-4 Free Night expires…") is not a nights count, wherever "free" sits on it.
  { name: 'R3-29 Hyatt: award price and Category 1-4 free night expiry', text: `World of Hyatt\nExplorist\nPoints 33,400\nFree night awards from 3,500 points\nCategory 1-4 Free Night expires 05/31/2027\nExplorist status through 02/28/2027\nQualifying nights 33\nBase points 40,000`,
    expect: { program: 'hyatt', balance: 33400, tier: 'Explorist', exp: '2027-02-28', progress: 33, alt: 40000 } },
  // Captions with a year ("Miles earned in 2026", "Tier Points 2026/27") are still captions; what was earned isn't the balance.
  { name: 'FB5 Flying Blue: miles earned this year vs balance (caption has a year)', text: `Flying Blue\nGold\nMiles earned in 2026\n32,100\nMiles balance\n58,760\nXP 210 / 300`,
    expect: { program: 'flyingblue', balance: 58760, tier: 'Gold' } },
  { name: 'B19 Aeroplan: points earned in 2026 vs points balance, SQC tile', text: `Aeroplan\n50K\nPoints earned in 2026\n62,800\nPoints balance\n145,900\nSQC\n52,000`,
    expect: { program: 'aeroplan', balance: 145900, progress: 52000 } },
  { name: "V4 Aeroplan: SQC caption with a year, tier '35K' above it", text: `Aeroplan\n35K\nSQC earned in 2026\n41,200\nPoints\n112,400`,
    expect: { program: 'aeroplan', balance: 112400, progress: 41200 } },
  { name: 'V3 BA: Tier Points caption with membership year', text: `British Airways Club\nSilver\nTier Points 2026/27\n1,240\nAvios\n52,118`,
    expect: { program: 'ba', balance: 52118, tier: 'Silver' } },
  { name: 'V5 Emirates: Tier Miles caption with a year', text: `Emirates Skywards\nGold\nTier Miles in 2026\n42,300\nSkywards Miles\n86,420`,
    expect: { program: 'emirates', balance: 86420, tier: 'Gold' } },
  // Member numbers: an airline prefix before spaced digit groups, and a lone "number" caption over its number.
  { name: 'EK1 Emirates: spaced membership number with airline prefix', text: `Skywards\nGold\nSkywards Miles\n86,420\nTier Miles\n42,300 / 50,000\nTier valid until 31 May 2027\nMembership number EK 123 456 789`,
    expect: { program: 'emirates', balance: 86420, tier: 'Gold', exp: '2027-05-31', member: 'EK123456789' } },
  { name: "B10 Flying Blue: 'Flying Blue number' caption over a spaced number", text: `Flying Blue\nGold\nFlying Blue number\n1234 567 890\nMiles\n45 600`,
    expect: { program: 'flyingblue', balance: 45600, member: '1234567890' } },
  // Dates: day-first programs, "expiry", "validity date", and a card's MM/YY "Valid thru".
  { name: 'EK2 Emirates: numeric day-first date', text: `Emirates Skywards\nPlatinum\nSkywards Miles 210,450\nTier Miles 152,000\nTier valid until 05/06/2027`,
    expect: { program: 'emirates', balance: 210450, tier: 'Platinum', exp: '2027-06-05' } },
  { name: "B6 Singapore: 'Membership expiry:' date", text: `KrisFlyer\nElite Gold\nKrisFlyer miles 44,200\nMembership expiry: 31 Jan 2028`,
    expect: { program: 'singapore', balance: 44200, tier: 'Elite Gold', exp: '2028-01-31' } },
  { name: "B7 Qatar: 'Tier expiry date'", text: `Privilege Club\nGold\nAvios 64,210\nQpoints 215\nTier expiry date 31/08/2027`,
    expect: { program: 'qatar', balance: 64210, tier: 'Gold', exp: '2027-08-31' } },
  { name: "B8 Turkish: 'Card validity date'", text: `Miles&Smiles\nElite\nMiles 31,400\nCard validity date 30.11.2027`,
    expect: { program: 'turkish', balance: 31400, tier: 'Elite', exp: '2027-11-30' } },
  { name: "B9 Turkish digital card: 'Valid thru 11/27' (MM/YY)", text: `Miles&Smiles\nElite Plus Card\nMiles 31,400\nValid thru 11/27`,
    expect: { program: 'turkish', balance: 31400, tier: 'Elite Plus', exp: '2027-11-30' } },
  // ---------- Probe round 4
  // A date on a merged line that names a level, with no points or miles word just before it, is the status's.
  { name: 'R4 United long merged line', text: `United MileagePlus Premier Gold Miles 98,765 PQP 13,020 PQF 33 Valid through Jan 31, 2028`,
    expect: { program: 'united', balance: 98765, tier: 'Premier Gold', progress: 13020, alt: 33, exp: '2028-01-31' } },
  // The program named right under a "Transfer points" heading is where points go, not whose screen it is.
  { name: 'R4 Chase transfer screen to World of Hyatt', text: `Transfer points\nWorld of Hyatt\n1:1 ratio\nYour Ultimate Rewards balance\n120,000 points\nPoints to transfer 20,000`,
    expect: { program: 'chase', balance: 120000 } },
  // A member number labeled only "No.".
  { name: "R4 Accor: day-month-year written date (member number labeled only 'No.')", text: `ALL Accor Live Limitless\nGold status until 31 Dec 2027\nPoints expiry date 15/06/2028\n2 450 Reward points\nNo. 3081 0312 3456 7890`,
    expect: { program: 'accor', balance: 2450, tier: 'Gold', exp: '2027-12-31', member: '3081031234567890' } },
  // A "Lifetime <level>" heading above the balance is a status, not a lifetime-miles caption.
  { name: 'R4 Marriott Lifetime Platinum', text: `Marriott Bonvoy\nLifetime Platinum Elite\n82,416 Points\nNights this year 14\nLifetime nights 612`,
    expect: { program: 'marriott', balance: 82416, tier: 'Platinum Elite', progress: 14 } },
  { name: 'R4 Hilton Lifetime Diamond heading', text: `Hilton Honors\nLifetime Diamond\n412,030 Points\nNights 12`,
    expect: { program: 'hilton', balance: 412030, tier: 'Diamond' } },
  { name: 'R4 AA Lifetime Platinum heading', text: `AAdvantage\nLifetime Platinum\n45,210 miles\nLoyalty Points 12,000`,
    expect: { program: 'american', balance: 45210, tier: 'Platinum', progress: 12000 } },
  { name: 'R4 United Lifetime Premier Gold heading', text: `MileagePlus\nLifetime Premier Gold\n88,000 miles\nPQP 3,200`,
    expect: { program: 'united', balance: 88000, tier: 'Premier Gold', progress: 3200 } },
];
